
name: Deploy

on:
  release:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Tweet
      if: ${{ endsWith(github.ref_name, '.0') }}
      run: echo This is a minor/major release
        
